server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: 'http://localhost:9090'
          predicates:
            - Path=/api/user/**
          filters:
            - 'AuthenticationFilter'
        - id: product
          uri: 'http://localhost:8090'
          predicates:
            - Path=/api/product/**
          filters:
            - 'AuthenticationFilter'
        - id: auth
          uri: 'http://localhost:9080'
          predicates:
            - Path=/auth/**
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka